#------------------------------------
# file: ./src/backend/template.yaml
#
# Maintainer: Dmitrii Demitov
# email: dmitrii_demitov@epam.com
#------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM template for deploying Lambda function.

Resources:

# Build the API Gateway and setup an API Key
  ApiGatewayEndpoint:
    Type: 'AWS::Serverless::Api'
    Description: Gateway API
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization

  # Setup the Lambda Function
  ServerlessFunction:
    Type: 'AWS::Serverless::Function'
    Description: Serverless function
    Properties:
      Runtime: python3.9
      CodeUri: .
      Handler: backend.lambda_handler
      Description:
      MemorySize: 128
      Timeout: 45
      Events:
        HttpApiAnyPathPostMethod:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /
            Method: POST
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: "*"

Outputs:
  ApiGateway:
    Description: "The URL is:"
    Value: !Sub "https://${ApiGatewayEndpoint}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  ApiKey:
    Description: "You can find your API Key in the AWS console: (Put in the request HEADER as 'x-api-key')"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${ApiGatewayEndpointApiKey}"
