#------------------------------------
# file: ./src/backend/template.yaml
#
# Maintainer: Dmitrii Demitov
# email: dmitrii_demitov@epam.com
#------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM template for deploying Lambda function.

Resources:

  # Setup the Lambda Function
  ServerlessFunction:
    Type: 'AWS::Serverless::Function'
    Description: Serverless function
    Properties:
      Runtime: python3.9
      CodeUri: .
      Handler: backend.lambda_handler
      Description:
      MemorySize: 128
      Timeout: 45
      # Environment:
      #   Variables:
      #     API_KEY: !Ref ApiKey
      #     CLIENT_ID: !Ref ClientId
      # sam package \
        # --template-file template.yml \
        # --s3-bucket demitov-v13 \
        # --output-template-file packaged.yml
      # sam deploy \
        # --template-file packaged.yml \
        # --stack-name STACK_NAME \
        # --capabilities CAPABILITY_IAM \
        # --parameter-overrides ApiKey=${API_KEY} ClientId=${CLIENT_ID}
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - https://*
          AllowMethods:
            - POST
          AllowHeaders:
            - X-Api-Key
            - Content-Type
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: "*"

Outputs:
  ServerlessFunctionEndpoint:
    Description: "Lambda function URL Endpoint"
    Value:
      Fn::GetAtt: ServerlessFunctionUrl.FunctionUrl
